### ISSUE TITLE
allowed_devices_room

### ISSUE THREAD

**Issue by olsins** [domcross/fhem-skill#8]
Settings auf Mycroft.ai edited
Homebridge room on Fhem created
dummy Licht defined
genericDeviceType light set as attribute

--> getting following error

 File "/opt/mycroft/skills/fhem-skill.domcross/__init__.py", line 156, in handle_switch_intent
    fhem_device = self._find_device(device, allowed_types, room)
  File "/opt/mycroft/skills/fhem-skill.domcross/__init__.py", line 740, in _find_device
    device_candidates = self.fhem.get(room=self.allowed_devices_room,
AttributeError: 'FhemSkill' object has no attribute 'allowed_devices_room'
16:13:36.261 - ConfigurationSkill - INFO - Remote configuration updated
  ^--- NEWEST ---^

**Comment by olsins** [comment]
I don't know if the error ist related, but when I start Mycroft I also get this one:
CSRF token requested for server that doesn't know CSRF

--> The newest Fhem version is installed 
also  attr WEB.* csrfToken <beliebige Folge aus Zeichen und Zahlen> did not help

**Comment by domcross** [comment]
When `self.allowed_devices_room` is not initialized then there was no succesful connection to FHEM-Server during setup/initialization of the skill. Yes, this might be related to the CSRF-token error you get. I think the problem is the configuration of your FHEM system. 

My `FHEMWEB` device for the Mycroft connection looks like following:
```
Internals:
   CSRFTOKEN  csrf_XXXXXXXXXXXXXXXX
   DEF        8087 global
   FD         XX
   FUUID      XXXX-XXXX-XXXX-XXXX
   FVERSION   01_FHEMWEB.pm:0.198780/2019-07-21
   NAME       WEBmycroft
   NR         XXX
   NTFY_ORDER 50-WEBmycroft
   PORT       8087
   STATE      Initialized
   TYPE       FHEMWEB
   READINGS:
     2019-07-26 20:47:30   state           Initialized
Attributes:
   hiddenroom ...list of rooms I dont want the device to know...
   room       Homebridge,Unsorted
```
and here the is my `allowed` device that is "protecting" WEBmycroft:
```
Internals:
   FUUID      XXXX-XXXX-XXXX-XXXX
   FVERSION   96_allowed.pm:0.190460/2019-03-27
   NAME       allowedWEBmycroft
   NR         XXX
   STATE      validFor:WEBmycroft
   TYPE       allowed
   validFor   WEBmycroft
   READINGS:
     2019-07-26 20:47:30   state           validFor:WEBmycroft
Attributes:
   basicAuth  { "$user:$password" eq "user:pass" }
   disable    0
   validFor   WEBmycroft
```
User and password must match the skill configuration at home.mycroft.ai

Nevertheless thanks for reporting this. I will try to improve the skill by adding some more checks if FHEM is reachable and skill was properly initialized...

**Comment by olsins** [comment]
I got it to work over telnet. Simply entered a telnet password in fhem, changed to telnet in the skill and it all works smooth :-) 

Nevertheless I gonna check out your configuration later! Thanks a lot for the skill!

**Comment by domcross** [comment]
Great! I did not test the telnet connection myself, good to hear that it works as designed.

**Comment by domcross** [comment]
closing issue as it seems to be working now
